[log]
  # enable traefik daemon INFO logging to console
  level = "INFO"

# enable traefik web logging to console
[accessLog]

[api]
  dashboard = true
  debug = true

[providers]
  # use docker for service discovery
  [providers.docker]
    exposedByDefault = false

[entryPoints]
  # define http, https, and traefik admin entrypoints
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.web-traefik-secure]
    address = ":8080"

# use letsencrypt for SSL
[certificatesResolvers.letsencrypt.acme]
  email = "{{ cookiecutter.email }}"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "web"
