#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# push images to ECR
# NOTE: you must log in first

echo "Pushing images..."

docker push {{ cookiecutter.aws_account_id }}.dkr.ecr.{{ cookiecutter.aws_region }}.amazonaws.com/{{ cookiecutter.project_slug }}/django
docker push {{ cookiecutter.aws_account_id }}.dkr.ecr.{{ cookiecutter.aws_region }}.amazonaws.com/{{ cookiecutter.project_slug }}/redis

echo "Done!"
